server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: rubrum
    password: rubrum

keypair:
  public-key: /project/security/public_key.der
  private-key: /project/security/private_key.der
