spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/rubrum
    driver-class-name: org.postgresql.Driver
    username: rubrum
    password: rubrum
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

swagger:
  title: Simple Secured Api
  description: A simple secured api sample with kotlin
  termsOfServiceUrl:
  contact: Richou
  license: Apache licence version 2.0
  licenseUrl:
  version: 2.0


server:
  port: 8006